name: iirs-env
channels:
  - defaults
  - conda-forge
channel_priority: flexible
dependencies:
  # python version compatible with Operon
  - python=3.9
  
  # install python distutils and build packages
  - python-devtools

  # other dependencies, installed via pip
  - pip
  - pip:
    # utility modules
    - numpy==1.20.3
    - filelock==3.0.12
    - scipy==1.6.3
    - jax==0.2.13
    - jaxlib==0.1.67

    # regressor modules
    - scikit-learn==0.24.2
    - itea==1.1.0

    # explainer modules (fixed versions due deprecation warnings of its dependences)
    - shap==0.40.0
    - sage-importance==0.0.4
    - interpret==0.2.7
    - lime==0.2.0.1

    # iirsBenchmark testing
    - pytest
    - pytest-html

    # post hoc analysis
    - notebook
    - nb_conda_kernels
    - matplotlib==3.4.2
    - seaborn==0.11.1
    - pandas==1.1.0
    - pyparsing==2.4.7
    - sympy==1.9
    - matplotlib-venn